# Generated by Django 5.2 on 2025-04-09 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the product event (UUID4)', primary_key=True, serialize=False, verbose_name='Event ID')),
                ('event_data', models.JSONField(help_text='Complete product event data in JSON format after deduplication', verbose_name='Event Data')),
            ],
            options={
                'verbose_name': 'Product Event',
                'verbose_name_plural': 'Product Events',
            },
        ),
    ]
